# Generated by Django 4.2.2 on 2023-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_bloodrequest_request_by_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
