# Generated by Django 4.2.2 on 2023-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
    ]
